kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  {{- if eq .Release.Namespace "open-cluster-management-agent-addon" }}
  name: cluster-proxy-addon-agent-impersonator
  {{- else }}
  name: cluster-proxy-addon-agent-impersonator:{{ .Release.Namespace }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-proxy-addon-agent-impersonator
subjects:
  - kind: ServiceAccount
    name: cluster-proxy
    namespace: {{ .Release.Namespace }}
