apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: cluster-proxy-service-proxy-server-certificates
data:
  "tls.crt": {{ .Values.serviceProxySecretCert }}
  "tls.key": {{ .Values.serviceProxySecretKey }}
